name: test

on:
  push:
  pull_request:

jobs:
  deno:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: test
        run: |
          deno test --coverage
          deno coverage --lcov > coverage.lcov
      - name: upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: coverage.lcov
          token: ${{ secrets.CODECOV_TOKEN }}
